CREATE TABLE categories (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(20),
    dateIn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateUp TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
 )