CREATE TABLE carts (
    id INT NOT NULL AUTO_INCREMENT,
    userId INT NOT NULL,
    quantity INT NOT NULL,
    dateIn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateUp TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX idx_userId
ON carts (userId);