CREATE TABLE orderDetails (
    id INT NOT NULL AUTO_INCREMENT,
    productId INT NOT NULL,
    orderId INT NOT NULL,
    amount INT NOT NULL,
    dateIn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateUp TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (productId) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (orderId) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE
);
